import blog1 from "../assets/images/blog1.png";
import blog2 from "../assets/images/blog2.png";
import blog3 from "../assets/images/blog3.png";
import blog4 from "../assets/images/blog4.png";

const BlogContent = [
  {
    id: 0,
    name: "Sundarbans",
    blogImg: blog1,
    content:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla, repellat similique hic numquam obcaecati temporibus suscipit alias sapiente, totam repudiandae nostrum odio sed! Non odio, explicabo voluptatem itaque, dicta aspernatur nesciunt sint ipsum sed dignissimos numquam ullam cupiditate, consequuntur expedita? Nam mollitia voluptates assumenda asperiores, optio commodi quibusdam iusto inventore officia nostrum perferendis aspernatur recusandae obcaecati suscipit! Voluptatibus nisi aliquam voluptas, illum doloremque consequatur, architecto nostrum sed repellat minus officia ex quidem ut sapiente, sit ipsa laboriosam voluptatum iusto vero. Maxime omnis ut quis iusto odio deserunt dicta placeat ipsam voluptatem temporibus inventore dolores, pariatur similique iste voluptates. Accusantium iste ipsum perferendis doloribus expedita facilis dolore in repellat necessitatibus labore id odio, aut sed modi. Vel cum obcaecati architecto dolor sunt quidem, beatae suscipit, ab aliquid illum error minus aliquam voluptates, dolore in. Ad animi voluptas veritatis quia facilis neque, sed distinctio perspiciatis dolores repudiandae id cupiditate nam accusantium unde quae qui ab est quidem porro hic nostrum ducimus accusamus. Omnis, beatae nisi maiores impedit delectus alias placeat recusandae officia fugit repudiandae possimus natus maxime incidunt laudantium, aspernatur minus quia quam cumque nulla rem? Facere tempore non necessitatibus delectus dicta distinctio doloribus? Totam, quasi mollitia a sint repellat ipsa assumenda. Sit praesentium ipsum quo soluta et accusamus sint explicabo, id blanditiis? Necessitatibus, tempora delectus! Earum cum nemo odio laborum iste molestias, incidunt veniam culpa necessitatibus, qui ratione atque, quam tempore sed voluptates deserunt! Eum ullam ut totam aliquid nesciunt laudantium distinctio, error odit minima doloribus porro! Odit nobis ducimus blanditiis! Quam quo culpa illo laudantium soluta ipsum harum, saepe earum quasi cumque, incidunt ut totam repellat! Possimus itaque, atque eius perferendis maxime, odit magnam veritatis ipsam recusandae mollitia error, nostrum non nulla ratione provident reprehenderit? Quasi, minima eos eligendi saepe quidem magnam labore reiciendis itaque dolorum, ab culpa iusto repellendus.",
  },
  {
    id: 1,
    name: "Chittagong Hill Tracks",
    blogImg: blog2,
    content:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla, repellat similique hic numquam obcaecati temporibus suscipit alias sapiente, totam repudiandae nostrum odio sed! Non odio, explicabo voluptatem itaque, dicta aspernatur nesciunt sint ipsum sed dignissimos numquam ullam cupiditate, consequuntur expedita? Nam mollitia voluptates assumenda asperiores, optio commodi quibusdam iusto inventore officia nostrum perferendis aspernatur recusandae obcaecati suscipit! Voluptatibus nisi aliquam voluptas, illum doloremque consequatur, architecto nostrum sed repellat minus officia ex quidem ut sapiente, sit ipsa laboriosam voluptatum iusto vero. Maxime omnis ut quis iusto odio deserunt dicta placeat ipsam voluptatem temporibus inventore dolores, pariatur similique iste voluptates. Accusantium iste ipsum perferendis doloribus expedita facilis dolore in repellat necessitatibus labore id odio, aut sed modi. Vel cum obcaecati architecto dolor sunt quidem, beatae suscipit, ab aliquid illum error minus aliquam voluptates, dolore in. Ad animi voluptas veritatis quia facilis neque, sed distinctio perspiciatis dolores repudiandae id cupiditate nam accusantium unde quae qui ab est quidem porro hic nostrum ducimus accusamus. Omnis, beatae nisi maiores impedit delectus alias placeat recusandae officia fugit repudiandae possimus natus maxime incidunt laudantium, aspernatur minus quia quam cumque nulla rem? Facere tempore non necessitatibus delectus dicta distinctio doloribus? Totam, quasi mollitia a sint repellat ipsa assumenda. Sit praesentium ipsum quo soluta et accusamus sint explicabo, id blanditiis? Necessitatibus, tempora delectus! Earum cum nemo odio laborum iste molestias, incidunt veniam culpa necessitatibus, qui ratione atque, quam tempore sed voluptates deserunt! Eum ullam ut totam aliquid nesciunt laudantium distinctio, error odit minima doloribus porro! Odit nobis ducimus blanditiis! Quam quo culpa illo laudantium soluta ipsum harum, saepe earum quasi cumque, incidunt ut totam repellat! Possimus itaque, atque eius perferendis maxime, odit magnam veritatis ipsam recusandae mollitia error, nostrum non nulla ratione provident reprehenderit? Quasi, minima eos eligendi saepe quidem magnam labore reiciendis itaque dolorum, ab culpa iusto repellendus.",
  },
  {
    id: 2,
    name: "Srimagal",
    blogImg: blog3,
    content:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla, repellat similique hic numquam obcaecati temporibus suscipit alias sapiente, totam repudiandae nostrum odio sed! Non odio, explicabo voluptatem itaque, dicta aspernatur nesciunt sint ipsum sed dignissimos numquam ullam cupiditate, consequuntur expedita? Nam mollitia voluptates assumenda asperiores, optio commodi quibusdam iusto inventore officia nostrum perferendis aspernatur recusandae obcaecati suscipit! Voluptatibus nisi aliquam voluptas, illum doloremque consequatur, architecto nostrum sed repellat minus officia ex quidem ut sapiente, sit ipsa laboriosam voluptatum iusto vero. Maxime omnis ut quis iusto odio deserunt dicta placeat ipsam voluptatem temporibus inventore dolores, pariatur similique iste voluptates. Accusantium iste ipsum perferendis doloribus expedita facilis dolore in repellat necessitatibus labore id odio, aut sed modi. Vel cum obcaecati architecto dolor sunt quidem, beatae suscipit, ab aliquid illum error minus aliquam voluptates, dolore in. Ad animi voluptas veritatis quia facilis neque, sed distinctio perspiciatis dolores repudiandae id cupiditate nam accusantium unde quae qui ab est quidem porro hic nostrum ducimus accusamus. Omnis, beatae nisi maiores impedit delectus alias placeat recusandae officia fugit repudiandae possimus natus maxime incidunt laudantium, aspernatur minus quia quam cumque nulla rem? Facere tempore non necessitatibus delectus dicta distinctio doloribus? Totam, quasi mollitia a sint repellat ipsa assumenda. Sit praesentium ipsum quo soluta et accusamus sint explicabo, id blanditiis? Necessitatibus, tempora delectus! Earum cum nemo odio laborum iste molestias, incidunt veniam culpa necessitatibus, qui ratione atque, quam tempore sed voluptates deserunt! Eum ullam ut totam aliquid nesciunt laudantium distinctio, error odit minima doloribus porro! Odit nobis ducimus blanditiis! Quam quo culpa illo laudantium soluta ipsum harum, saepe earum quasi cumque, incidunt ut totam repellat! Possimus itaque, atque eius perferendis maxime, odit magnam veritatis ipsam recusandae mollitia error, nostrum non nulla ratione provident reprehenderit? Quasi, minima eos eligendi saepe quidem magnam labore reiciendis itaque dolorum, ab culpa iusto repellendus.",
  },
  {
    id: 3,
    name: "Rangamati",
    blogImg: blog4,
    content:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla, repellat similique hic numquam obcaecati temporibus suscipit alias sapiente, totam repudiandae nostrum odio sed! Non odio, explicabo voluptatem itaque, dicta aspernatur nesciunt sint ipsum sed dignissimos numquam ullam cupiditate, consequuntur expedita? Nam mollitia voluptates assumenda asperiores, optio commodi quibusdam iusto inventore officia nostrum perferendis aspernatur recusandae obcaecati suscipit! Voluptatibus nisi aliquam voluptas, illum doloremque consequatur, architecto nostrum sed repellat minus officia ex quidem ut sapiente, sit ipsa laboriosam voluptatum iusto vero. Maxime omnis ut quis iusto odio deserunt dicta placeat ipsam voluptatem temporibus inventore dolores, pariatur similique iste voluptates. Accusantium iste ipsum perferendis doloribus expedita facilis dolore in repellat necessitatibus labore id odio, aut sed modi. Vel cum obcaecati architecto dolor sunt quidem, beatae suscipit, ab aliquid illum error minus aliquam voluptates, dolore in. Ad animi voluptas veritatis quia facilis neque, sed distinctio perspiciatis dolores repudiandae id cupiditate nam accusantium unde quae qui ab est quidem porro hic nostrum ducimus accusamus. Omnis, beatae nisi maiores impedit delectus alias placeat recusandae officia fugit repudiandae possimus natus maxime incidunt laudantium, aspernatur minus quia quam cumque nulla rem? Facere tempore non necessitatibus delectus dicta distinctio doloribus? Totam, quasi mollitia a sint repellat ipsa assumenda. Sit praesentium ipsum quo soluta et accusamus sint explicabo, id blanditiis? Necessitatibus, tempora delectus! Earum cum nemo odio laborum iste molestias, incidunt veniam culpa necessitatibus, qui ratione atque, quam tempore sed voluptates deserunt! Eum ullam ut totam aliquid nesciunt laudantium distinctio, error odit minima doloribus porro! Odit nobis ducimus blanditiis! Quam quo culpa illo laudantium soluta ipsum harum, saepe earum quasi cumque, incidunt ut totam repellat! Possimus itaque, atque eius perferendis maxime, odit magnam veritatis ipsam recusandae mollitia error, nostrum non nulla ratione provident reprehenderit? Quasi, minima eos eligendi saepe quidem magnam labore reiciendis itaque dolorum, ab culpa iusto repellendus.",
  },
];

export default BlogContent;
